"""Use-case-oriented persistence interfaces owned by the application."""

from collections.abc import Iterable, Mapping, Sequence
from datetime import date
from typing import Protocol

from ftx_paper.contracts import MarketBar
from .records import (
    AuthToken, ProcessLease, ReplayRun, RuntimeContract, RuntimeStatus,
    StoredEvent,
)


class EventRepository(Protocol):
    def append(self, event_type: str, payload: Mapping[str, object], idempotency_key: str | None = None) -> bool: ...
    def read_recent(self, limit: int = 100) -> Sequence[StoredEvent]: ...


class MarketBarRepository(Protocol):
    def append(self, bars: Iterable[MarketBar], source: str) -> None: ...
    def read_for_date(self, session_date: str) -> Sequence[MarketBar]: ...


class ReplayRepository(Protocol):
    def create(self, run_id: str, request: Mapping[str, object]) -> ReplayRun: ...
    def transition(self, run_id: str, expected_status: str, new_status: str, result: Mapping[str, object] | None = None, error: str | None = None) -> bool: ...
    def get(self, run_id: str) -> ReplayRun | None: ...


class EventQueryRepository(Protocol):
    def read_decisions(self, session_date: str | None = None, limit: int = 50, before_id: int | None = None, session_name: str | None = None) -> Sequence[StoredEvent]: ...
    def read_lifecycle(self, decision_ids: Iterable[str]) -> Sequence[StoredEvent]: ...
    def counts(self) -> Mapping[str, Mapping[str, int]]: ...


class MarketBarQueryRepository(Protocol):
    def read_dates(self) -> Sequence[str]: ...
    def stats(self) -> Mapping[str, object]: ...


class ReplayQueryRepository(Protocol):
    def recent(self, limit: int = 100) -> Sequence[ReplayRun]: ...
    def summaries(self, limit: int = 100) -> Sequence[ReplayRun]: ...
    def latest_for_date(self, session_date: str) -> ReplayRun | None: ...
    def clear_for_date(self, session_date: str) -> int: ...


class RuntimeStatusRepository(Protocol):
    def get(self) -> RuntimeStatus: ...
    def update(self, status: Mapping[str, object]) -> None: ...
    def patch(self, updates: Mapping[str, object]) -> None: ...


class ProcessLeaseRepository(Protocol):
    def acquire(self, service: str) -> ProcessLease: ...
    def release(self, service: str, instance_id: str) -> None: ...


class RuntimeContractRepository(Protocol):
    def get(self, exchange: str, underlying: str, role: str) -> RuntimeContract | None: ...
    def save(self, contract: RuntimeContract) -> bool: ...


class ExpiryRepository(Protocol):
    def get_all(self) -> frozenset[str]: ...
    def replace(self, expiry_dates: Iterable[str], source: str) -> bool: ...


class AuthTokenRepository(Protocol):
    def save(self, token: AuthToken) -> None: ...
    def get_valid(self, provider: str, token_date: date) -> AuthToken | None: ...
